phase: train

device: cpu  # Use GPU for maximum performance

dataset:
  name: AFD

feature:
  generator: LSTMCRF
  labels:
    [
      "PERSON_NAME",
      "PHONE_NUMBER",
      "SOCIAL_NUMBER",
      "CARD_ISSUER",
      "GEOPOLITICAL_ENTITIES",
      "EMAIL",
    ]

model:
  name: LSTMCRF
  version: null
  use_pretrained: true                    # Use pre-trained model instead of training from scratch
  pretrained_model: "flair/ner-english-ontonotes"  # Pre-trained Flair model to use
  batch_size: 32                          # Optimized batch size for GPU processing
