phase: train

device: cpu  # Use GPU for maximum performance

dataset:
  name: Conll2003
  sample_size: null  # Set to null for full dataset, or specify number for sampling (e.g., 5000)

feature:
  generator: LSTMCRF
  labels: ['PERSON_NAME', 'LOCATION', 'ORGANIZATION']

model:
  name: LSTMCRF
  version: null
  use_pretrained: true                    # Use pre-trained model instead of training from scratch
  pretrained_model: "flair/ner-english-ontonotes"  # Pre-trained Flair model to use
  batch_size: 32                          # Optimized batch size for GPU processing
