phase: train

dataset:
  name: AFD

feature:
  generator: spaCy
  labels:
    [
      'FAC',
      'LOC',
      'NORP',
      'GPE',
      'PERSON'
    ]

model:
  name: spaCy
  version: en_core_web_trf
